## 02 Numpy užduotys

In [3]:
import numpy as np

### 1. Sukurkite vektorių su skaičiais nuo 1 iki 10

In [20]:
arr_1 = np.arange(1,11)
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2. Sukurkite vektorių iš 10 nulių

In [6]:
arr_2 = np.zeros(10)
arr_2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 3.	Sukurkite vektorių iš 10 vienetų

In [22]:
arr_3 = np.ones(10)
arr_3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 4. Sukurkite vektorių iš 10 ketvertų

In [23]:
arr_3.fill(4)
arr_3

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

### 5. Sukurkite vektorių iš lyginių skaičių nuo 0 iki 100

In [24]:
arr_4 = np.arange(0,101,2)
arr_4

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### 6. Sukurkite matricą iš 25 narių, pradedant 1, baigiant 25. Priskirkite ją kintamajam.

In [25]:
arr_5 = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25]])
arr_5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### 7. Iš matricos ištraukite skaičių 12

In [26]:
arr_5[2,1]

12

### 8. Iš matricos ištraukite paskutinę eilutę.

In [27]:
arr_5[4]

array([21, 22, 23, 24, 25])

### 9. Iš matricos ištraukite submatricą: 1, 2, 3\ 6, 7, 8\ 11,12,13

In [29]:
arr_5[: 3, : 3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

### 10.	Iš matricos ištraukite submatricą: 7, 8, 9, 10\ 12, 13, 14, 15\ 17, 18, 19, 20

In [30]:
arr_5[1 : 4, 1 :]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20]])

### 11. Iš matricos ištraukite submatricą: 16, 17, 18 \ 21, 22, 23

In [31]:
arr_5[3 :, : 3]

array([[16, 17, 18],
       [21, 22, 23]])

### 12. Sukurkite vektorių iš 20 atsitiktinių reikšmių nuo 0 iki 1. Priskirkite kintamajam.

In [32]:
arr_6 = np.random.uniform(0,1,20)
arr_6

array([0.46265965, 0.52188248, 0.13324015, 0.60596429, 0.5036882 ,
       0.77941191, 0.99798083, 0.93881218, 0.79675438, 0.12525727,
       0.22150763, 0.6215783 , 0.42161451, 0.67738779, 0.06865588,
       0.88526359, 0.99214379, 0.64747824, 0.72160275, 0.21693864])

### 13.	Suraskite didžiausią reikšmę masyve ir jos indeksą. (naudoti max() ir .argmax())

In [35]:
max_value = np.max(arr_6)
max_index = np.argmax(arr_6)
max_value, max_index 

(0.9979808299149394, 6)

### 14.	Suraskite mažiausią reikšmę ir jos indeksą. (naudoti min() ir .argmin())

In [36]:
min_value = np.min(arr_6)
min_index = np.argmin(arr_6)
min_value, min_index

(0.06865588410973356, 14)

### 15.	Atspausdinkite šios matricos duomenų tipą

In [37]:
arr_6.dtype

dtype('float64')